name: Instagram Bot
on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Download session data
      uses: actions/download-artifact@v3
      with:
        name: session-data
        path: ./
        
    - name: Run bot
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTA_USER }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTA_PASS }}
        HF_API_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python main.py
      
    - name: Upload session data
      uses: actions/upload-artifact@v3
      with:
        name: session-data
        path: |
          session.json
          welcomed_users.pkl
        retention-days: 1
